version: '3.8'

services:
  backend:
    build: ./backend
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: vue_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: python:3.9-slim
    container_name: sqlite_db
    command: tail -f /dev/null
    volumes:
      - ./database.sqlite3:/app/database.sqlite3

volumes:
  mysql_data: