# Generated by Django 5.0.3 on 2024-11-01 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=11)),
                ('logradouro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
                ('inicio_data', models.DateField()),
                ('fim_data', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormacaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universidade', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
                ('inicio_data', models.DateField()),
                ('fim_data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estudante_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.dadospessoais')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidatos.contato')),
                ('dados_pessoais', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidatos.dadospessoais')),
                ('experiencia', models.ManyToManyField(to='candidatos.experiencia')),
                ('formacao_academica', models.ManyToManyField(to='candidatos.formacaoacademica')),
                ('habilidades', models.ManyToManyField(to='candidatos.habilidade')),
            ],
        ),
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to='candidatos.contato')),
                ('dados_pessoais', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to='candidatos.dadospessoais')),
                ('experiencias', models.ManyToManyField(related_name='candidatos', to='candidatos.experiencia')),
                ('formacoes_academicas', models.ManyToManyField(related_name='candidatos', to='candidatos.formacaoacademica')),
                ('habilidades', models.ManyToManyField(related_name='candidatos', to='candidatos.habilidade')),
            ],
        ),
    ]
